worker_processes 1;
daemon off;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 7860;
        server_name _;

        # Serve Gradio App
        location / {
            proxy_pass http://127.0.0.1:7861;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_read_timeout 86400;
        }

        # Serve Showdown Client Static Files
        location /client/ {
            alias /app/client/;
            index testclient.html index.html;
        }

        # Proxy Showdown Server WebSockets
        location /showdown/websocket {
            proxy_pass http://127.0.0.1:8000/showdown/websocket;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_read_timeout 86400;
        }

        location /api/ {
            proxy_pass http://127.0.0.1:8000/api/;
            proxy_set_header Host $host;
        }
        
        location /action.php {
            proxy_pass http://127.0.0.1:8000/action.php;
            proxy_set_header Host $host;
        }
    }
}
